# Generated by Django 5.1 on 2024-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='score',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
    ]
