# Generated by Django 5.1 on 2024-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_ebook_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='release_date',
            field=models.FloatField(),
        ),
    ]
