# Generated by Django 5.1 on 2024-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_alter_ebook_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='photo',
            field=models.ImageField(default='a.png', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='release_date',
            field=models.DateField(),
        ),
    ]
