# Generated by Django 5.1 on 2024-08-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_ebook_photo_alter_ebook_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='photo',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
