# Generated by Django 5.1 on 2024-08-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_alter_ebook_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('fantacy', 'Fantacy'), ('technology', 'Technology')], max_length=20),
        ),
    ]
